# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: announcements.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "API.Announcements.Query" do
    optional :limit, :int32, 1
    optional :offset, :int32, 2
  end
  add_message "API.Announcements.Id" do
    optional :id, :int32, 1
  end
  add_message "API.Announcements.SearchResult" do
    optional :total, :int32, 1
    repeated :hit, :message, 2, "API.Announcements.SearchResult.Hit"
  end
  add_message "API.Announcements.SearchResult.Hit" do
    optional :id, :int32, 1
    optional :title, :string, 2
    optional :authorName, :string, 3
    optional :publishedAt, :int64, 4
  end
  add_message "API.Announcements.LookupResult" do
    optional :announcement, :message, 1, "API.Announcements.Announcement"
  end
  add_message "API.Announcements.Announcement" do
    optional :id, :int32, 1
    optional :title, :string, 2
    optional :authorName, :string, 3
    optional :publishedAt, :int64, 4
    optional :body, :string, 5
  end
end

module API
  module Announcements
    Query = Google::Protobuf::DescriptorPool.generated_pool.lookup("API.Announcements.Query").msgclass
    Id = Google::Protobuf::DescriptorPool.generated_pool.lookup("API.Announcements.Id").msgclass
    SearchResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("API.Announcements.SearchResult").msgclass
    SearchResult::Hit = Google::Protobuf::DescriptorPool.generated_pool.lookup("API.Announcements.SearchResult.Hit").msgclass
    LookupResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("API.Announcements.LookupResult").msgclass
    Announcement = Google::Protobuf::DescriptorPool.generated_pool.lookup("API.Announcements.Announcement").msgclass
  end
end
