# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: announcements.proto for package 'API.Announcements'

require 'grpc'
require 'announcements_pb'

module API
  module Announcements
    module Announcements
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'API.Announcements.Announcements'

        rpc :Search, Query, SearchResult
        rpc :Get, Id, LookupResult
      end

      Stub = Service.rpc_stub_class
    end
  end
end
